
/*CRIAÇÃO BANCO DE DADOS*/
CREATE  DATABASE DIRETORIA_TESTE
GO

/*CRIAÇÃO DA TABELA DAS CATEGORIAS*/
CREATE TABLE TAB_CATEGORIA (
	ID_CATEGORIA INT PRIMARY KEY NOT NULL,
	NOME_CATEGORIA VARCHAR (80) NOT NULL,	
) 
GO


/*CRIAÇÃO TABELA DOS PRODUTOS*/
CREATE TABLE PRODUTOS(
	ID_PRODUTO INT PRIMARY KEY NOT NULL,
	NOME_DESCRICAO VARCHAR(50) NOT NULL,
	MARCA VARCHAR(30) NOT NULL,
	PRECO NUMERIC(10,2) NOT NULL,
	DATA_FABRICACAO VARCHAR (20) NOT NULL,
	VALIDADE VARCHAR (20) NOT NULL,
	ID_CATEGORIA INT,
)
GO

/*CRIAÇÃO TABELA DAS ALTERAÇÕES OCORRIDAS EM PRODUTOS*/
CREATE TABLE HIST_PRODUTOS(
	SEQUENCIAL INT PRIMARY KEY IDENTITY (100,5),
	ID_PRODUTO INT,
	NOME_DESCRICAO VARCHAR(60),
	MARCA VARCHAR(30) NOT NULL,
	ID_CAT VARCHAR(30),
	PRECO_ANTIGO NUMERIC(10,2),
	PRECO_NOVO NUMERIC(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(20),
	MENSAGEM VARCHAR(70)
)
GO

/* FAZENDO AS INSERÇÕES */

INSERT INTO PRODUTOS (ID_PRODUTO, NOME_DESCRICAO, MARCA, PRECO, DATA_FABRICACAO, VALIDADE, ID_CATEGORIA)
VALUES
 	(10,'Arroz Branco', 'Tio João', 30.00, 'Abr/24' , 'Dez/24', 10),
	(20,'Feijão Preto', 'Carioca', 12.00, 'Jan/24' , 'Jul/24',10),
	(30,'Macarrão Espagueti ', 'Todeschini', 9.50, 'Nov/23' , 'Mai/24',10),
	(40,'Extrato Tomate', 'Elefante', 4.99, 'Dez/23' , 'Jun/24',10),
	(50,'Água Sanitária', 'Ki-Boa', 7.90, 'Nov/23' , 'Nov/24',20),
	(60,'Desinfetante', 'Pinho Sol', 12.90, 'Jun/23' , 'Jun/24',20),
	(70,'Shampoo', 'Loréal', 19.75, 'Out/23' , 'Out/24',30),
	(80,'Vinho Tinto Seco', 'Terra Vega', 24.90, 'Nov/22' , 'Indeterminada',40),
	(90,'Wyski', 'Red Label', 109.90, 'Nov/23' , 'Indeterminada',40)	
GO

/* CRIANDO O GATILHO DE BACKUP */

CREATE TRIGGER Trg_Atualiza_Preco
ON DBO.PRODUTOS
FOR UPDATE AS
IF UPDATE(PRECO)  /*faz disparar o gatilho apenas se alterar na coluna 'PRECO'*/

BEGIN
	 INSERT INTO HIST_PRODUTOS (ID_PRODUTO, NOME_DESCRICAO, MARCA, ID_CAT, PRECO_ANTIGO, PRECO_NOVO,
	 DATA, USUARIO, MENSAGEM)
	 SELECT D.ID_PRODUTO, D.NOME_DESCRICAO, D.MARCA, D.ID_CATEGORIA ,  D.PRECO , I.PRECO, GETDATE(), SUSER_NAME(),'Atenção Preço Alterado'
	 FROM DELETED D, INSERTED I
	 WHERE D.ID_PRODUTO = I.ID_PRODUTO
END

PRINT 'TRIGGER EXECUTADA COM SUCESSO'
GO



/* FAZENDO TDS OPERAÇÕES PARA TESTE...*/
select * from PRODUTOS
go

select * from HIST_PRODUTOS
go

select * from TAB_CATEGORIA
go

delete  from PRODUTOS
go

UPDATE PRODUTOS 
SET MARCA='CICA'
WHERE ID_PRODUTO=40
GO

UPDATE PRODUTOS 
SET PRECO=69.90
WHERE ID_PRODUTO=90
GO

UPDATE PRODUTOS 
SET PRECO=PRECO * 1.1
WHERE ID_CATEGORIA=40
GO


/*OBSERVAÇÕES GERAIS: Está td dentro do SSMS.  
ESTANDO DENTRO DE UM BANCO ‘A’,  PODE INSERIR DRETO PARA OUTRO BANCO ‘B’ , CONFORME TABELA EXISTENTE EM BANCO B.
BANCO ‘EMPRESA’  EM USO ATUAL.
INSERT INTO DIRETORIA_TESTE.dbo.TAB_CATEGORIA 
VALUES 
(10, 'Produtos Limpeza', 'Atualização de Preços')
GO

SELECT * FROM BD_TESTE.DBO.TAB_CATEGORIA 
GO
*/